Developpement WEB/Projet FlOpEDT/FlOpEDT/base/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
# 
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from django.conf.urls import url, include,patterns
from django.urls import path
from . import views
from . import statistics
from django.views.generic import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

app_name="base"

urlpatterns = [
    # favicon
    # ----------------------------
    url(views.fav_regexp,
        views.favicon,
        name="favicon"),

    # directly reachable by users
    # ----------------------------
    url(r'^semaine-type$', views.stype, name="stype"),
    url(r'^aide$', views.aide, name="aide"),
    url(r'^decale$', views.decale, name="decale"),    
    url(r'^contact$', views.contact, name="contact"),
    url(r'^((?P<an>\d{4}))?(/(?P<semaine>\d{1,2}))?$', views.edt, name="edt"),
    url(r'^tv(/(?P<semaine>\d+))?(/(?P<an>\d+))?$', views.edt_light, name="edt_light"),

    # exchanges with the db via django
    # ---------------------------------

    # from db to screen
    url(r'^fetch_cours_pl/(?P<year>\d+)/(?P<week>\d+)/(?P<num_copy>\d+)$', views.fetch_cours_pl, name="fetch_cours_pl"),
    url(r'^fetch_cours_pp/(?P<year>\d+)/(?P<week>\d+)/(?P<num_copy>\d+)$', views.fetch_cours_pp, name="fetch_cours_pp"),
    url(r'^fetch_dispos/(?P<year>\d+)/(?P<week>\d+)$', views.fetch_dispos, name="fetch_dispos"),
    url(r'^fetch_stype$', views.fetch_stype, name="fetch_stype"),
    url(r'^fetch_decale$', views.fetch_decale, name="fetch_decale"),
    url(r'^fetch_decale$', statistics.fetch_room_activity, name="fetch_room_activity"),
    url(r'^fetch_bknews/(?P<year>\d+)/(?P<week>\d+)$', views.fetch_bknews, name="fetch_bknews"),
    url(r'^fetch_groups$', views.fetch_groups, name="fetch_groups"),    
    url(r'^fetch_rooms$', views.fetch_rooms, name="fetch_rooms"),    
    url(r'^fetch_unavailable_rooms/(?P<year>\d+)/(?P<week>\d+)$', views.fetch_unavailable_rooms, name="fetch_unavailable_rooms"),
    url(r'^fetch_all_tutors/$', views.fetch_all_tutors, name="fetch_all_tutors"),
    url(r'^fetch_all_versions/$', views.fetch_all_versions, name="fetch_all_versions"),
    url(r'^fetch_week_infos/(?P<year>\d+)/(?P<week>\d+)$', views.fetch_week_infos, name="fetch_week_infos"),

    # statistics
    # ---------------------------------
    path('statistics/', include([
        path('', statistics.index, name="statistics"),
        path('rooms/', statistics.fetch_room_activity, name="room_activity"),
        path('tutors/', statistics.fetch_tutor_hours, name="tutor_hours"),
    ])),

    # from screen to db
    url(r'^change_edt$', views.edt_changes, name="edt_changes"),
    url(r'^change_dispos/$', views.dispos_changes, name="dispos_changes"),
    url(r'^change_decale$', views.decale_changes, name="decale_changes"),


    # predefined
    # ------------
    
    #formulaire
    patterns('',
        url(r'^$', views.post_list),
        url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail),
        url(r'^post/new/$', views.post_new, name='post_new'),
    )
]

# https://pypi.python.org/pypi/django-live-log
# https://github.com/abdullatheef/django_live_log

Developpement WEB/Projet FlOpEDT/FlOpEDT/ics/urls.py
from django.urls import path
from ics.feeds import TutorEventFeed, RoomEventFeed, GroupEventFeed

from ics import views

app_name = 'ics'

urlpatterns = [
    path(r'', views.index, name="index"),
    path(r'tutor/<slug:tutor>.ics', TutorEventFeed(), name="tutor"),
    path(r'room/<slug:room>.ics', RoomEventFeed(), name="room"),
    path(r'group/<slug:training_programme>/<slug:group>.ics', GroupEventFeed(), name="group")
]

Developpement WEB/Projet FlOpEDT/FlOpEDT/people/urls.py
# -*- coding: utf-8 -*-

# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
# 
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from people.student import AddStudent, ChangeStudent
from people.tutor import AddFullStaffTutor, AddSupplyStaffTutor, AddBIATOSTutor
from people.tutor import ChangeFullStaffTutor, ChangeSupplyStaffTutor, ChangeBIATOSTutor
from . import views

app_name="people"

urlpatterns = [
#    url(r'^login', views.login, name="login"),
    url(r'^login/$',
        auth_views.LoginView.as_view(template_name='people/login.html'),
        name='login'),
    url(r'^logout/$',
        auth_views.LogoutView.as_view( next_page= '/'),
        name='logout'),
    url(r'^password-reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='people/password_reset_form.html',
            email_template_name='people/password_reset_email.html',
            subject_template_name='people/password_reset_subject.txt',
            success_url=reverse_lazy('people:password_reset_done')),
        name='password_reset'),
    url(r'^pwd-reset-done/$',
        auth_views.PasswordResetDoneView.as_view(
            template_name='people/password_reset_done.html'),
        name='password_reset_done'),
    url(r'^pwd-reset-complete/$',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='people/password_reset_complete.html'),
        name='password_reset_complete'),
    url(r'^password-change/$',
        auth_views.PasswordChangeView.as_view(
            template_name='people/password_change_form.html',
            success_url=reverse_lazy('people:password_change_done')),
        name='password_change'),
    url(r'^pwd-chg-done/$',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='people/password_change_done.html'),
        name='password_change_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='people/password_reset_confirm.html',
            success_url=reverse_lazy('people:password_reset_complete')),
        name='password_reset_confirm'),
    url(r'^add/some/(?P<kind>[A-Za-z]*)$',
        views.redirect_add_people_kind,
        name="add_redirect"),
    url(r'^add/student/$',
        AddStudent.as_view(),
        name="add_student"),
    url(r'^add/fullstaff/$',
        AddFullStaffTutor.as_view(),
        name="add_fullstaff"),
    url(r'^add/supplystaff/$',
        AddSupplyStaffTutor.as_view(),
        name="add_supplystaff"),
    url(r'^add/biatos/$',
        AddBIATOSTutor.as_view(),
        name="add_BIATOS"),
    url(r'^change/some/$',
        views.redirect_change_people_kind,
        name="change_redirect"),
    url(r'^change/student/$',
        ChangeStudent.as_view(),
        name="change_student"),
    url(r'^change/fullstaff/$',
        ChangeFullStaffTutor.as_view(),
        name="change_fullstaff"),
    url(r'^change/supplystaff/$',
        ChangeSupplyStaffTutor.as_view(),
        name="change_supplystaff"),
    url(r'^change/biatos/$',
        ChangeBIATOSTutor.as_view(),
        name="change_BIATOS"),
	url(r'^fetch_tutors/$',
        views.fetch_tutors,
        name="fetch_tutors"),
    ]

Developpement WEB/Projet FlOpEDT/FlOpEDT/solve_board/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
# 
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from django.conf.urls import url, include

from solve_board import views

app_name="solve_board"

urlpatterns = [
    url(r'^fetch_context/(?P<train_prog>[a-zA-Z]\w{1,4})/(?P<year>\d{4})/(?P<week>\d{2})/$', views.fetch_context, name="fetch_context"),
    url(r'^main/$', views.main_board, name="main_board"),
#    url(r'^run/(?P<timestamp>[0-9-]+)?$', views.run, name="run"),
]

Developpement WEB/Projet FlOpEDT/FlOpEDT/base/forms.py
# -*- coding: utf-8 -*-

# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
# 
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from django import forms
from people.models import Tutor, FullStaff


class ContactForm(forms.Form):
    sender = forms.EmailField(label='Votre adresse mail :')
    recipient = forms.CharField(
        label='Destinataire :',
        max_length=4,
        help_text="Acronyme : 4 caractères max")
    subject = forms.CharField(
        label='Sujet du mail :',
        max_length=100,
        help_text="100 caractères max")
    message = forms.CharField(label='Corps du mail :',
                              max_length=2000,
                              widget=forms.Textarea())

    def clean_recipient(self):
        recipient = self.cleaned_data['recipient']
        if not Tutor.objects.filter(username=recipient).exists():
            raise forms.ValidationError("Cette personne n'existe pas.")
        return recipient

Developpement WEB/Projet FlOpEDT/FlOpEDT/templates/base.html
<!-- This file is part of the FlOpEDT/FlOpScheduler project.               -->
<!-- Copyright (c) 2017                                                    -->
<!-- Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.           -->
<!--                                                                       -->
<!-- This program is free software: you can redistribute it and/or modify  -->
<!-- it under the terms of the GNU Affero General Public License as        -->
<!-- published by the Free Software Foundation, either version 3 of the    -->
<!-- License, or (at your option) any later version.                       -->
<!--                                                                       -->
<!-- This program is distributed in the hope that it will be useful, but   -->
<!-- WITHOUT ANY WARRANTY; without even the implied warranty of            -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU      -->
<!-- Affero General Public License for more details.                       -->
<!--                                                                       -->
<!-- You should have received a copy of the GNU Affero General Public      -->
<!-- License along with this program. If not, see                          -->
<!-- <http://www.gnu.org/licenses/>.                                       -->
<!--                                                                       -->
<!-- You can be released from the requirements of the license by purchasing-->
<!-- a commercial license. Buying such a license is mandatory as soon as   -->
<!-- you develop activities involving the FlOpEDT/FlOpScheduler software   -->
<!-- without disclosing the source code of your own applications.          -->

{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
<style>
</style>
<link rel="stylesheet" href="{% static "base/header.css" %}" />
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png?v=5AeyQYqgW7">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png?v=5AeyQYqgW7">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png?v=5AeyQYqgW7">
<link rel="manifest" href="/site.webmanifest?v=5AeyQYqgW7">
<link rel="mask-icon" href="/safari-pinned-tab.svg?v=5AeyQYqgW7" color="#858585">
<link rel="shortcut icon" href="/favicon.ico?v=5AeyQYqgW7">
<meta name="msapplication-TileColor" content="#048c04">
<meta name="theme-color" content="#000000">
<script src="{% static 'base/jquery.min.js' %}"></script>
<script src="{% static 'base/d3.v4.min.js' %}"></script>
<script src="{% static 'base/loader.js' %}"></script>
<script>var url_logo = "{% static 'base/logo-clock.svg' %}";</script>
<!-- script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script -->
<title>{% block title %}Emplois du temps{% endblock %}</title>
</head>
<body>
  <div id="loader" class="loader" style="visibility:hidden;"></div>
<!--<header>Emplois du temps</header>-->
    <nav id="menu-edt">
      <a class="hide_this_link" target="_blank" href="https://framagit.org/flopedt/flopedt" id="live-logo"  style="padding: 0px 0px 0px 0px; float: left">
			</a>
			<div id="full_logo">     
				<span id="acro_logo">Fl<span id=opRed >Op</span>EDT<br></span>
				{% autoescape off %}
				<span id="head_logo">
					<!--{{ image }}-->
				</span>
				{% endautoescape %}
				<a id="agpl" href="https://www.gnu.org/licenses/agpl-3.0.en.html">
					<img src="{% static 'base/agplv3-88x31.png'%}" height="31" width="88" alt="AGPL v.3"/>
				</a>
			</div>

       {% block nav %}
       <ul>
				{% if department %}
				<li><a href="{% url "base:edt" department %}">Consulter</a></li>
				<li><a href="{% url "base:decale" department %}">Décaler/Annuler</a></li>
				<li><a href="{% url "base:stype" department %}">Semaine type</a></li>
				<li><a href="{% url "ics:index" department %}">iCal</a></li>
				<li><a href="{% url "base:aide" department %}">Aide</a></li>
				<li><a href="{% url "base:contact" department %}">Contact</a></li>
				{% if user.is_authenticated and user.is_superuser %}
					<li><a href="{% url "solve_board:main_board" department %}">Générer</a></li>
					<li><a href="{% url "base:statistics" department %}">Statistiques</a></li>
					<li><a href="{% url "admin:index" %}">Admin</a></li>
				{% endif %}
				{% endif %}
				<li style="float:right">
				{% if user.is_authenticated %}
						{% if department %}
							<a href="{% url "people:logout" %}?next={% url "base:edt" department %}">Déconnexion</a>
						{% elif not 'accounts' in request.path %}
							<a href="{% url "people:logout" %}?next={{request.path}}">Déconnexion</a>
						{% else %}
							<a href="{% url "people:logout" %}">Déconnexion</a>
						{% endif %}
				{% else %}
					<a href="{% url "people:login" %}?next={{request.path}}">Se connecter</a>
				{% endif %}
				</li>
				<li style="float:right">{% if user.is_authenticated %}
					<a href="{% url "people:change_redirect" %}">Connecté&middot;e sous {{ user.username }} </a> {% endif %}
				</li>
       </ul>
       {% endblock %}
   </nav>
   <section id="content">
       {% block content %}{% endblock %}
   </section>

   <script src="{% static 'base/logo.js' %}";></script>
   <script>
     
   </script>  

</body>
</html>