Developpement WEB/Projet FlOpEDT/FlOpEDT/ics/urls.py
from django.urls import path
from ics.feeds import TutorEventFeed, RoomEventFeed, GroupEventFeed

from ics import views

app_name = 'ics'

urlpatterns = [
    path(r'', views.index, name="index"),
    path(r'tutor/<slug:tutor>.ics', TutorEventFeed(), name="tutor"),
    path(r'room/<slug:room>.ics', RoomEventFeed(), name="room"),
    path(r'group/<slug:training_programme>/<slug:group>.ics', GroupEventFeed(), name="group")
]

Developpement WEB/Projet FlOpEDT/FlOpEDT/people/urls.py
# -*- coding: utf-8 -*-

# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
# 
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from people.student import AddStudent, ChangeStudent
from people.tutor import AddFullStaffTutor, AddSupplyStaffTutor, AddBIATOSTutor
from people.tutor import ChangeFullStaffTutor, ChangeSupplyStaffTutor, ChangeBIATOSTutor
from . import views

app_name="people"

urlpatterns = [
#    url(r'^login', views.login, name="login"),
    url(r'^login/$',
        auth_views.LoginView.as_view(template_name='people/login.html'),
        name='login'),
    url(r'^logout/$',
        auth_views.LogoutView.as_view( next_page= '/'),
        name='logout'),
    url(r'^password-reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='people/password_reset_form.html',
            email_template_name='people/password_reset_email.html',
            subject_template_name='people/password_reset_subject.txt',
            success_url=reverse_lazy('people:password_reset_done')),
        name='password_reset'),
    url(r'^pwd-reset-done/$',
        auth_views.PasswordResetDoneView.as_view(
            template_name='people/password_reset_done.html'),
        name='password_reset_done'),
    url(r'^pwd-reset-complete/$',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='people/password_reset_complete.html'),
        name='password_reset_complete'),
    url(r'^password-change/$',
        auth_views.PasswordChangeView.as_view(
            template_name='people/password_change_form.html',
            success_url=reverse_lazy('people:password_change_done')),
        name='password_change'),
    url(r'^pwd-chg-done/$',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='people/password_change_done.html'),
        name='password_change_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='people/password_reset_confirm.html',
            success_url=reverse_lazy('people:password_reset_complete')),
        name='password_reset_confirm'),
    url(r'^add/some/(?P<kind>[A-Za-z]*)$',
        views.redirect_add_people_kind,
        name="add_redirect"),
    url(r'^add/student/$',
        AddStudent.as_view(),
        name="add_student"),
    url(r'^add/fullstaff/$',
        AddFullStaffTutor.as_view(),
        name="add_fullstaff"),
    url(r'^add/supplystaff/$',
        AddSupplyStaffTutor.as_view(),
        name="add_supplystaff"),
    url(r'^add/biatos/$',
        AddBIATOSTutor.as_view(),
        name="add_BIATOS"),
    url(r'^change/some/$',
        views.redirect_change_people_kind,
        name="change_redirect"),
    url(r'^change/student/$',
        ChangeStudent.as_view(),
        name="change_student"),
    url(r'^change/fullstaff/$',
        ChangeFullStaffTutor.as_view(),
        name="change_fullstaff"),
    url(r'^change/supplystaff/$',
        ChangeSupplyStaffTutor.as_view(),
        name="change_supplystaff"),
    url(r'^change/biatos/$',
        ChangeBIATOSTutor.as_view(),
        name="change_BIATOS"),
	url(r'^fetch_tutors/$',
        views.fetch_tutors,
        name="fetch_tutors"),
    ]

Developpement WEB/Projet FlOpEDT/FlOpEDT/people/models.py
# -*- coding: utf-8 -*-

# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
# 
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.



from django.db import models
from django.contrib.auth.models import AbstractUser
from base.models import Department

# Create your models here.


class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_tutor = models.BooleanField(default=False)
    rights = models.PositiveSmallIntegerField(verbose_name="Droits particuliers",
                                              default=0)
    # 0b azmyx en binaire
    # x==1 <=> quand "modifier Cours" coché, les cours sont colorés
    #          avec la dispo du prof
    # y==1 <=> je peux changer les dispos de tout le monde
    # m==1 <=> je peux modifier l'emploi du temps comme bon me semble
    # FUTUR
    # z==1 <=> je peux changer les dispos des vacataires d'un module dont
    #          je suis responsable
    # a==1 <=> je peux surpasser les contraintes lors de la modification
    #          de cours

    def uni_extended(self):
        ret = self.username + '<'
        if self.is_student:
            ret += 'S'
        if self.is_tutor:
            ret += 'T'
        ret += '>'
        ret += '(' + str(self.rights) + ')'
        return ret

    class Meta:
       ordering = ['username',]        
        

class Tutor(User):
    FULL_STAFF = 'fs'
    SUPP_STAFF = 'ss'
    BIATOS = 'bi'
    TUTOR_CHOICES = ((FULL_STAFF, "Full staff"),
                     (SUPP_STAFF, "Supply staff"),
                     (BIATOS, "BIATOS"))
    status = models.CharField(max_length=2,
                              choices=TUTOR_CHOICES,
                              verbose_name="Status",
                              default=FULL_STAFF)
    pref_slots_per_day = models.PositiveSmallIntegerField(
        verbose_name="How many slots per day would you prefer ?",
        default=4)
    departments =  models.ManyToManyField(Department, blank=True)   

    def uni_extended(self):
        ret = super(Tutor,self).uni_extended()
        ret += '-' + self.status + '-' + 'S' + str(self.pref_slots_per_day)
        return ret


class FullStaff(Tutor):
    # deprected since multi departements insertion
    department = models.CharField(max_length=50, default='INFO', null=True, blank=True)
    is_iut = models.BooleanField(default=True)

    def uni_extended(self):
        ret = super(FullStaff,self).uni_extended()
        ret += '-D' + self.department + '-'
        if not self.is_iut:
            ret += 'n'
        ret += 'IUT'
        return ret

    class Meta:
        verbose_name = 'FullStaff' 


class SupplyStaff(Tutor):
    employer = models.CharField(max_length=50,
                                verbose_name="Employeur ?")
    position = models.CharField(max_length=50)
    field = models.CharField(max_length=50,
                             verbose_name="Domaine ?")
    def uni_extended(self):
        ret = super(SupplyStaff,self).uni_extended()
        ret += '-Emp:' + self.employer + '-'
        ret += '-Pos:' + self.position + '-'
        ret += '-Dom:' + self.field
        return ret

    class Meta:
        verbose_name = 'SupplyStaff'


class BIATOS(Tutor):
    def uni_extended(self):
        return super(BIATOS,self).uni_extended()

    class Meta:
        verbose_name = 'BIATOS'

# --- Notes sur Prof ---
#    MinDemiJournees=models.BooleanField(
#       verbose_name="Min Demi-journées?", default=False)
#    unparjour=models.BooleanField(verbose_name="Un créneau par jour?",
#                                  default=False)
# # (biatos | vacataire) => TPeqTD=false (donc 3h TP <=> 2h TD)
# # 1h CM <=> 1.5h TD
# TPeqTD = models.BooleanField()self.periode


class Student(User):  # for now: representative
    belong_to = models.ManyToManyField('base.Group',
                                       blank=True)

    def __str__(self):
        return str(self.username) + '(G:' + str(self.belong_to) + ')'

Developpement WEB/Projet FlOpEDT/FlOpEDT/people/forms.py
# -*- coding: utf-8 -*-

# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
# 
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.db import transaction

from .models import Student, User, FullStaff, SupplyStaff, BIATOS, Tutor
from base.models import Group

class AddStudentForm(UserCreationForm):
    gps = forms.ModelMultipleChoiceField(
        queryset=Group.objects.filter(basic=True),
        widget=forms.CheckboxSelectMultiple,
        required=False,
        help_text='Les groupes auquels vous appartenez'
    )

    class Meta(UserCreationForm.Meta):
        model = Student

    @transaction.atomic
    def save(self):
        student = super(AddStudentForm, self).save(commit=False)
        student.is_student = True
        student.save()
        student.belong_to.add(*self.cleaned_data.get('gps'))
        return student


class ChangeStudentForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = Student


class ChangeFullStaffTutorForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = FullStaff


class ChangeSupplyStaffTutorForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = SupplyStaff

class ChangeBIATOSTutorForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = BIATOS



class AddFullStaffTutorForm(UserCreationForm):
    dept = forms.CharField(max_length=50, help_text='Département')
    pref_slots_per_day = forms.IntegerField(required=False,
                                            help_text='Nombre de créneaux préférés par jour')
    is_iut = forms.BooleanField()

    class Meta(UserCreationForm.Meta):
        model = FullStaff
        fields = ('email', 'username', 'first_name', 'last_name')

    def __init__(self, *args, **kwargs):
        super(AddFullStaffTutorForm, self).__init__(*args, **kwargs)
        for key in self.fields:
            self.fields[key].required = True
            
    @transaction.atomic
    def save(self):
        fs = super(AddFullStaffTutorForm, self).save(commit=False)
        data = self.cleaned_data
        fs.is_tutor = True
        fs.status = Tutor.FULL_STAFF
        fs.pref_slots_per_day = data.get('pref_slots_per_day')
        fs.department = data.get('dept')
        fs.is_iut = data.get('is_iut')
        fs.save()
        return fs

    
class AddSupplyStaffTutorForm(UserCreationForm):
    employer = forms.CharField(max_length=50, help_text='Employeur')
    position = forms.CharField(max_length=50,
                               help_text='Qualité')
    field = forms.CharField(max_length=50,
                             help_text="Domaine")

    class Meta(UserCreationForm.Meta):
        model = SupplyStaff
        fields = ('email', 'username', 'first_name', 'last_name')

    def __init__(self, *args, **kwargs):
        super(AddSupplyStaffTutorForm, self).__init__(*args, **kwargs)
        for key in self.fields:
            self.fields[key].required = True
            
    @transaction.atomic
    def save(self):
        sus = super(AddFullStaffTutorForm, self).save(commit=False)
        data = self.cleaned_data
        sus.is_tutor = True
        sus.status = Tutor.SUPP_STAFF
        sus.employer = data.get('employer')
        sus.position = data.get('position')
        sus.field = data.get('field')
        sus.save()
        return sus

    
class AddBIATOSTutorForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = BIATOS
        fields = ('email', 'username', 'first_name', 'last_name')

    def __init__(self, *args, **kwargs):
        super(AddBIATOSTutorForm, self).__init__(*args, **kwargs)
        for key in self.fields:
            self.fields[key].required = True
            
    @transaction.atomic
    def save(self):
        bi = super(AddBIATOSTutorForm, self).save(commit=False)
        bi.is_tutor = True
        bi.status = Tutor.BIATOS
        bi.save()
        return bi

    

Developpement WEB/Projet FlOpEDT/FlOpEDT/people/views.py
# -*- coding: utf-8 -*-


from django.shortcuts import render
from django.http import Http404, HttpResponse
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from .models import Tutor
from .admin import TutorResource

def redirect_add_people_kind(req, kind):
    if kind == "stud":
        return redirect('people:add_student')
    elif kind == "full":
        return redirect('people:add_fullstaff')
    elif kind == "supp":
        return redirect('people:add_supplystaff')
    elif kind == "BIAT":
        return redirect('people:add_BIATOS')
    else:
        raise Http404("I don't know this kind of people.")


@login_required
def redirect_change_people_kind(req):
    if req.user.is_student:
        return redirect('people:change_student')
    if req.user.is_tutor:
        if req.user.tutor.status == Tutor.FULL_STAFF:
            return redirect('people:change_fullstaff')
        if req.user.tutor.status == Tutor.SUPP_STAFF:
            return redirect('people:change_supplystaff')
        if req.user.tutor.status == Tutor.BIATOS:
            return redirect('people:change_BIATOS')
    else:
        raise Http404("Who are you?")
            

def fetch_tutors(req):
	dataset = TutorResource().export(Tutor.objects.all())
	response = HttpResponse(dataset.csv,
                                content_type='text/csv')
	return response

Developpement WEB/Projet FlOpEDT/FlOpEDT/people/templates/people/adduser.html
<!-- This file is part of the FlOpEDT/FlOpScheduler project.               -->
<!-- Copyright (c) 2017                                                    -->
<!-- Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.           -->
<!--                                                                       -->
<!-- This program is free software: you can redistribute it and/or modify  -->
<!-- it under the terms of the GNU Affero General Public License as        -->
<!-- published by the Free Software Foundation, either version 3 of the    -->
<!-- License, or (at your option) any later version.                       -->
<!--                                                                       -->
<!-- This program is distributed in the hope that it will be useful, but   -->
<!-- WITHOUT ANY WARRANTY; without even the implied warranty of            -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU      -->
<!-- Affero General Public License for more details.                       -->
<!--                                                                       -->
<!-- You should have received a copy of the GNU Affero General Public      -->
<!-- License along with this program. If not, see                          -->
<!-- <http://www.gnu.org/licenses/>.                                       -->
<!--                                                                       -->
<!-- You can be released from the requirements of the license by purchasing -->
<!-- a commercial license. Buying such a license is mandatory as soon as   -->
<!-- you develop activities involving the FlOpEDT/FlOpScheduler software   -->
<!-- without disclosing the source code of your own applications.          -->

{% extends "base.html" %}

{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>

{% endblock %}

Developpement WEB/Projet FlOpEDT/FlOpEDT/people/templates/people/changeuser.html
<!-- This file is part of the FlOpEDT/FlOpScheduler project.               -->
<!-- Copyright (c) 2017                                                    -->
<!-- Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.           -->
<!--                                                                       -->
<!-- This program is free software: you can redistribute it and/or modify  -->
<!-- it under the terms of the GNU Affero General Public License as        -->
<!-- published by the Free Software Foundation, either version 3 of the    -->
<!-- License, or (at your option) any later version.                       -->
<!--                                                                       -->
<!-- This program is distributed in the hope that it will be useful, but   -->
<!-- WITHOUT ANY WARRANTY; without even the implied warranty of            -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU      -->
<!-- Affero General Public License for more details.                       -->
<!--                                                                       -->
<!-- You should have received a copy of the GNU Affero General Public      -->
<!-- License along with this program. If not, see                          -->
<!-- <http://www.gnu.org/licenses/>.                                       -->
<!--                                                                       -->
<!-- You can be released from the requirements of the license by purchasing -->
<!-- a commercial license. Buying such a license is mandatory as soon as   -->
<!-- you develop activities involving the FlOpEDT/FlOpScheduler software   -->
<!-- without disclosing the source code of your own applications.          -->

{% extends "base.html" %}

{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>

{% endblock %}

Developpement WEB/Projet FlOpEDT/FlOpEDT/people/templates/people/login.html
<!-- This file is part of the FlOpEDT/FlOpScheduler project.               -->
<!-- Copyright (c) 2017                                                    -->
<!-- Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.           -->
<!--                                                                       -->
<!-- This program is free software: you can redistribute it and/or modify  -->
<!-- it under the terms of the GNU Affero General Public License as        -->
<!-- published by the Free Software Foundation, either version 3 of the    -->
<!-- License, or (at your option) any later version.                       -->
<!--                                                                       -->
<!-- This program is distributed in the hope that it will be useful, but   -->
<!-- WITHOUT ANY WARRANTY; without even the implied warranty of            -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU      -->
<!-- Affero General Public License for more details.                       -->
<!--                                                                       -->
<!-- You should have received a copy of the GNU Affero General Public      -->
<!-- License along with this program. If not, see                          -->
<!-- <http://www.gnu.org/licenses/>.                                       -->
<!--                                                                       -->
<!-- You can be released from the requirements of the license by purchasing -->
<!-- a commercial license. Buying such a license is mandatory as soon as   -->
<!-- you develop activities involving the FlOpEDT/FlOpScheduler software   -->
<!-- without disclosing the source code of your own applications.          -->

{% extends "base.html" %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static "base/better.css" %}"/>
<script>
  var url_add = "{% url 'people:add_redirect' '' %}" ;
</script>
  
  
<div id="tools-main" style="padding:10px;">

  <div style="float: left; width:400px">    
    <fieldset style="width:300px">
      <legend>Authentification</legend>
      <form method="post" action="{% url 'people:login' %}" name="login">
	{% csrf_token %}
	<table>
	  <tr>
            <td>{{ form.username.label_tag }}</td>
            <td>{{ form.username }}</td>
	  </tr>
	  <tr>
            <td>{{ form.password.label_tag }}</td>
            <td>{{ form.password }}</td>
	  </tr>
	</table>
	
	<span><a href="{% url 'people:password_reset' %}">Mot de passe perdu ?</a></span>
	<input style="float:right" type="submit" value="Se connecter"/>
	<input type="hidden" name="next" value="{{ next }}"/>
      </form>
    </fieldset>
  </div>
  <div style="float: left; width:300px">
    {% if form.errors %}
    <p>Pas de correspondance entre le pseudo et le mot de passe. Réessayer.</p>
    {% endif %}
    
    {% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
      please login with an account that has access.</p>
    {% endif %}
    {% endif %}
    <p></p>
  </div>
<!--  <br style="clear: both" />-->
  
  <fieldset style="width:300px">
    <legend>Nouveau compte</legend>
    Je suis
    <form name="add">
      <input type="radio" id="stud" name="create" checked="checked">Étudiant&middot;e</input><br/>
      <input type="radio" id="full" name="create">Enseignant&middot;e permanent&middot;e</input><br/>
      <input type="radio" id="supp" name="create">Vacataire</input><br/>
      <input type="radio" id="BIAT" name="create">BIATOS</input><br/>
      <input style="float:right" type="button" value="Créer" onClick="create_user()"/>
    </form>
    <!--<p><a href="{ % url 'add_user' % }">Créer un nouveau compte</a></p>-->
  </fieldset>

  <script>
    function create_user() {
	var iam = document.forms['add'];
	var i = 0;
	while (!iam[i].checked) {
	    i++ ;
	}
	var url_go_add = url_add + iam[i].id ;
	console.log(url_go_add);
	window.location.href = url_go_add ;
    }
  </script>
  
{% endblock %}

Developpement WEB/Projet FlOpEDT/FlOpEDT/people/templates/people/password_change_confirm.html
<!-- This file is part of the FlOpEDT/FlOpScheduler project.               -->
<!-- Copyright (c) 2017                                                    -->
<!-- Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.           -->
<!--                                                                       -->
<!-- This program is free software: you can redistribute it and/or modify  -->
<!-- it under the terms of the GNU Affero General Public License as        -->
<!-- published by the Free Software Foundation, either version 3 of the    -->
<!-- License, or (at your option) any later version.                       -->
<!--                                                                       -->
<!-- This program is distributed in the hope that it will be useful, but   -->
<!-- WITHOUT ANY WARRANTY; without even the implied warranty of            -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU      -->
<!-- Affero General Public License for more details.                       -->
<!--                                                                       -->
<!-- You should have received a copy of the GNU Affero General Public      -->
<!-- License along with this program. If not, see                          -->
<!-- <http://www.gnu.org/licenses/>.                                       -->
<!--                                                                       -->
<!-- You can be released from the requirements of the license by purchasing -->
<!-- a commercial license. Buying such a license is mandatory as soon as   -->
<!-- you develop activities involving the FlOpEDT/FlOpScheduler software   -->
<!-- without disclosing the source code of your own applications.          -->

{% extends "base.html" %}

{% block title %}
Mot de passe oublié
{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static "base/better.css" %}"/>
<p>Mot de passe changé !</p>
{% endblock %}

Developpement WEB/Projet FlOpEDT/FlOpEDT/people/templates/people/password_reset_complete.html
<!-- This file is part of the FlOpEDT/FlOpScheduler project.               -->
<!-- Copyright (c) 2017                                                    -->
<!-- Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.           -->
<!--                                                                       -->
<!-- This program is free software: you can redistribute it and/or modify  -->
<!-- it under the terms of the GNU Affero General Public License as        -->
<!-- published by the Free Software Foundation, either version 3 of the    -->
<!-- License, or (at your option) any later version.                       -->
<!--                                                                       -->
<!-- This program is distributed in the hope that it will be useful, but   -->
<!-- WITHOUT ANY WARRANTY; without even the implied warranty of            -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU      -->
<!-- Affero General Public License for more details.                       -->
<!--                                                                       -->
<!-- You should have received a copy of the GNU Affero General Public      -->
<!-- License along with this program. If not, see                          -->
<!-- <http://www.gnu.org/licenses/>.                                       -->
<!--                                                                       -->
<!-- You can be released from the requirements of the license by purchasing -->
<!-- a commercial license. Buying such a license is mandatory as soon as   -->
<!-- you develop activities involving the FlOpEDT/FlOpScheduler software   -->
<!-- without disclosing the source code of your own applications.          -->

{% extends "base.html" %}

{% block title %}
Mot de passe oublié
{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static "base/better.css" %}"/>
    <p>
      Le mot de passe a été changé.<br/>
      <a href="{% url 'people:login' %}">
	Se connecter
      </a>
    </p>

{% endblock %}

Developpement WEB/Projet FlOpEDT/FlOpEDT/people/templates/people/password_reset_confirm.html
<!-- This file is part of the FlOpEDT/FlOpScheduler project.               -->
<!-- Copyright (c) 2017                                                    -->
<!-- Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.           -->
<!--                                                                       -->
<!-- This program is free software: you can redistribute it and/or modify  -->
<!-- it under the terms of the GNU Affero General Public License as        -->
<!-- published by the Free Software Foundation, either version 3 of the    -->
<!-- License, or (at your option) any later version.                       -->
<!--                                                                       -->
<!-- This program is distributed in the hope that it will be useful, but   -->
<!-- WITHOUT ANY WARRANTY; without even the implied warranty of            -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU      -->
<!-- Affero General Public License for more details.                       -->
<!--                                                                       -->
<!-- You should have received a copy of the GNU Affero General Public      -->
<!-- License along with this program. If not, see                          -->
<!-- <http://www.gnu.org/licenses/>.                                       -->
<!--                                                                       -->
<!-- You can be released from the requirements of the license by purchasing -->
<!-- a commercial license. Buying such a license is mandatory as soon as   -->
<!-- you develop activities involving the FlOpEDT/FlOpScheduler software   -->
<!-- without disclosing the source code of your own applications.          -->

{% extends "base.html" %}

{% block title %}
Mot de passe oublié
{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static "base/better.css" %}"/>
  {% if validlink %}
    <h3>Change password</h3>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Changer le mot de passe</button>
    </form>
  {% else %}
    <p>
      L'adresse de réinitialisation est invalide (déjà utilisée, par exemple).
      <a href="{% url 'people:password_reset'%}">
	Réréinitialiser !
      </a>
    </p>
  {% endif %}

{% endblock %}

Developpement WEB/Projet FlOpEDT/FlOpEDT/people/templates/people/password_reset_email.html
{% autoescape off %}
Pour réinitialiser votre mot de passe associé à votre compte {{ user.get_username }} sur FlOpEDT, accéder au lien suivant :

{{ protocol }}://{{ domain }}{% url 'people:password_reset_confirm' uidb64=uid token=token %}

(Soit en cliquant dessus, soit en copiant-collant l'adresse dans un navigateur quelconque.)
{% endautoescape %}