Developpement WEB/Projet FlOpEDT/FlOpEDT/ics/urls.py
from django.urls import path
from ics.feeds import TutorEventFeed, RoomEventFeed, GroupEventFeed

from ics import views

app_name = 'ics'

urlpatterns = [
    path(r'', views.index, name="index"),
    path(r'tutor/<slug:tutor>.ics', TutorEventFeed(), name="tutor"),
    path(r'room/<slug:room>.ics', RoomEventFeed(), name="room"),
    path(r'group/<slug:training_programme>/<slug:group>.ics', GroupEventFeed(), name="group")
]

Developpement WEB/Projet FlOpEDT/FlOpEDT/ics/models.py
from django.db import models

# Create your models here.

Developpement WEB/Projet FlOpEDT/FlOpEDT/ics/views.py
from django.shortcuts import render

from people.models import Tutor
from base.models import Group, Room

def index(request, **kwargs):
    enseignant_list = Tutor.objects.filter(is_active=True, is_tutor=True).order_by('username')
    groupe_list = Group.objects.filter(basic=True,
                                       train_prog__department=request.department)\
                               .order_by('train_prog__abbrev', 'nom')
    salle_list = [n.name.replace(' ','_') for n in Room.objects.all().order_by('name')]
    print(salle_list)
    context = { 'enseignants': enseignant_list, 'groupes':groupe_list, 'salles':salle_list }
    return render(request, 'ics/index.html', context=context)

Developpement WEB/Projet FlOpEDT/FlOpEDT/ics/templates/ics/index.html
<!-- This file is part of the FlOpEDT/FlOpScheduler project.               -->
<!-- Copyright (c) 2017                                                    -->
<!-- Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.           -->
<!--                                                                       -->
<!-- This program is free software: you can redistribute it and/or modify  -->
<!-- it under the terms of the GNU Affero General Public License as        -->
<!-- published by the Free Software Foundation, either version 3 of the    -->
<!-- License, or (at your option) any later version.                       -->
<!--                                                                       -->
<!-- This program is distributed in the hope that it will be useful, but   -->
<!-- WITHOUT ANY WARRANTY; without even the implied warranty of            -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU      -->
<!-- Affero General Public License for more details.                       -->
<!--                                                                       -->
<!-- You should have received a copy of the GNU Affero General Public      -->
<!-- License along with this program. If not, see                          -->
<!-- <http://www.gnu.org/licenses/>.                                       -->
<!--                                                                       -->
<!-- You can be released from the requirements of the license by purchasing -->
<!-- a commercial license. Buying such a license is mandatory as soon as   -->
<!-- you develop activities involving the FlOpEDT/FlOpScheduler software   -->
<!-- without disclosing the source code of your own applications.          -->

{% extends "base.html" %}

{% block title %} EDT {% endblock %}
{% block content %}
{% load static %}

<link rel="stylesheet" href="{% static "base/better.css" %}"/>

<div id="tools-main" style="padding:10px;">

    <h4>Abonnement iCal</h4>
    <p>Copiez le lien correspondant au calendrier auquel vous souhaitez vous abonner pour l'ajouter dans votre gestionnaire d'agenda.</p>
    
    <h4>Groupes</h4>
    <ul>
		{% for g in groupes %}
		<li><a href="{% url "ics:group" department g.train_prog.abbrev g.nom %}">{{ g.train_prog.abbrev }}/{{ g.nom }}</a></li>
		{% endfor %}
	</ul>
    
    <h4>Enseignants</h4>
    <ul>
		{% for e in enseignants %}
			<li><a href="{% url "ics:tutor" department e.username %}">{{ e.username }}</a></li>
		{% endfor %}
	</ul>
	
	<h4>Salles</h4>
    <ul>
		{% for s in salles %}
			<li><a href="{% url "ics:room" department s %}">{{ s }}</a></li>
		{% endfor %}
	</ul>

</div>
{% endblock %}